name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage codacy-coverage

    - name: Run tests with coverage
      run: |
        coverage run -m unittest BD1_test

    - name: Convert coverage report to Codacy format
      run: |
        coverage xml

    - name: Upload coverage report to Codacy
      run: |
        python-codacy-coverage -r coverage.xml
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
